export const fr = {
  appName: "riwak",
  tagline: "Commande rapide et fidÃ©litÃ© pour le cafÃ©",
  brand: {
    short: "riwak",
    full: "Riwak Coffee",
  },
  actions: {
    register: "CrÃ©er mon compte",
    login: "Se connecter",
    logout: "Se dÃ©connecter",
    addCustomer: "Ajouter un client",
    orderNow: "Commander maintenant",
    viewOrder: "Voir la commande",
    viewProfile: "Fiche",
    addToHome: "Ajouter Ã  lâ€™Ã©cran dâ€™accueil",
    dismiss: "Plus tard",
    redeem: "Utiliser",
    save: "Enregistrer",
    create: "Créer",
    edit: "Modifier",
    add: "Ajouter",
    refresh: "Actualiser",
    back: "Retour",
    confirm: "Confirmer",
    cancel: "Annuler",
    continue: "Continuer",
    record: "Enregistrer",
    stop: "ArrÃªter",
    listenAgain: "RÃ©Ã©couter",
    delete: "Supprimer",
    quickReorder: "Recommander",
    markTrusted: "Marquer comme rÃ©gulier",
    markLimited: "Limiter",
    useReward: "Utiliser rÃ©compense",
    addOneStamp: "+1 tampon",
    addTwoStamps: "+2 tampons",
    prepareSms: "PrÃ©parer le SMS",
  },
  common: {
    loading: "Chargementâ€¦",
    search: "Rechercher",
    notesOptional: "Notes, si besoin",
    noResults: "Aucun rÃ©sultat pour le moment.",
    emptyState: "Rien Ã  afficher pour lâ€™instant.",
    active: "Actif",
    inactive: "Inactif",
    today: "Aujourdâ€™hui",
    now: "Maintenant",
    minutesShort: "min",
    quantity: "QuantitÃ©",
    pickupTime: "Heure de retrait",
    pickupAddress: "Adresse de retrait",
    phoneNumber: "NumÃ©ro de tÃ©lÃ©phone",
    fullName: "Nom complet",
    loyaltyPin: "PIN fidÃ©litÃ©",
    memberId: "ID membre",
    password: "Mot de passe",
    email: "E-mail",
    price: "Prix",
    status: "Statut",
    sugar: "Sucre",
    each: "l'unitÃ©",
  },
  navCustomer: {
    home: "Accueil",
    menu: "Menu",
    rewards: "RÃ©compenses",
    account: "Compte",
  },
  navStaff: {
    orders: "Commandes",
    customers: "Clients",
    loyalty: "FidÃ©litÃ©",
    settings: "RÃ©glages",
  },
  landing: {
    eyebrow: "Commande mobile",
    title: "Riwak simplifie la pause cafÃ©.",
    subtitle:
      "Commandez en avance, payez au comptoir, rÃ©cupÃ©rez vite. FidÃ©litÃ© simple.",
    registerCardTitle: "Nouveau client",
    registerCardBody: "CrÃ©ez votre compte en moins dâ€™une minute.",
    returningCardTitle: "Nouvel appareil ?",
    returningCardBody: "Retrouvez votre compte avec votre tÃ©lÃ©phone et votre code de secours.",
    returningInlineBody:
      "Sur ce tÃ©lÃ©phone, vous restez connectÃ©.",
    staffCardTitle: "Espace Ã©quipe",
    staffCardBody: "AccÃ¨s barista et admin pour les commandes et le suivi client.",
    staffLinkBody: "AccÃ¨s barista et admin",
    installHintTitle: "Ajouter lâ€™app",
    installHintBody:
      "Gardez Riwak sur lâ€™Ã©cran dâ€™accueil pour ouvrir lâ€™app plus vite, mÃªme en boutique bondÃ©e.",
  },
  auth: {
    registerTitle: "CrÃ©er votre compte client",
    registerBody:
      "Entrez votre nom et votre numÃ©ro. Sur ce tÃ©lÃ©phone, vous resterez connectÃ© automatiquement.",
    loginTitle: "Connexion sur un nouvel appareil",
    loginBody:
      "Utilisez votre tÃ©lÃ©phone et votre code de secours uniquement si vous changez dâ€™appareil.",
    loginCreateHint: "Nouveau client ?",
    registerLoginHint: "DÃ©jÃ  inscrit ?",
    recoveryCodeLabel: "Code de secours",
    staffLoginTitle: "Connexion Ã©quipe",
    staffLoginBody: "AccÃ¨s sÃ©curisÃ© pour le personnel et lâ€™admin.",
    staffPasswordHint: "Le mot de passe est rÃ©servÃ© Ã  lâ€™Ã©quipe.",
    pinHelp:
      "Gardez ce code seulement pour retrouver votre compte sur un autre tÃ©lÃ©phone. Sur ce tÃ©lÃ©phone, vous restez connectÃ©.",
  },
  home: {
    greeting: (name: string, timeOfDay: "day" | "evening" = "day") =>
      `${timeOfDay === "evening" ? "Bonsoir" : "Bonjour"}, ${name}`,
    orderCardTitle: "Commander vite",
    orderCardBody: "Choisissez un article et un crÃ©neau de retrait.",
    activeOrderTitle: "Commande en cours",
    activeOrderBody: "Votre commande est dÃ©jÃ  en route.",
    loyaltyTitle: "FidÃ©litÃ©",
    rewardTitle: "RÃ©compense disponible",
    recentOrderTitle: "DerniÃ¨re commande",
    favoriteOrderTitle: "Commande favorite",
    memberIdTitle: "ID membre",
    memberIdHint: "Ã€ montrer au barista",
    trustCardTitle: "Niveau client",
  },
  menu: {
    title: "Menu",
    subtitle: "Une carte courte, rapide Ã  lire, facile Ã  configurer.",
    detailTitle: "DÃ©tail de lâ€™article",
    detailBody: "SÃ©lectionnez la quantitÃ© et ajoutez une note seulement si nÃ©cessaire.",
    orderButton: "Choisir le retrait",
  },
  order: {
    reviewTitle: "VÃ©rification de la commande",
    reviewBody: "Relisez, choisissez lâ€™heure de retrait, puis validez.",
    quickInstructionsTitle: "Instructions rapides",
    writtenNoteLabel: "Note Ã©crite",
    voiceNoteLabel: "Message vocal",
    voiceNoteHint: "Optionnel, 15 sec max.",
    voiceNotePreviewReady: "Message vocal prÃªt.",
    voiceNoteRecording: (seconds: number, maxSeconds: number) =>
      `Enregistrement ${seconds}s / ${maxSeconds}s`,
    voiceNoteUnsupported: "L'enregistrement vocal n'est pas disponible sur ce tÃ©lÃ©phone.",
    voiceNoteTooLong: "Le message vocal est trop long. Gardez-le trÃ¨s court.",
    voiceNotePlaybackUnavailable: "Le message vocal ne peut pas Ãªtre lu pour le moment.",
    successTitle: "Commande envoyÃ©e",
    successBody: "Lâ€™Ã©quipe voit la commande tout de suite.",
    liveStatusTitle: "Suivi de commande",
    liveStatusBody: "Suivez lâ€™Ã©tat en temps rÃ©el sur votre tÃ©lÃ©phone.",
    pickupNow: "Retrait maintenant",
    pickupIn: (minutes: number) => `Retrait dans ${minutes} min`,
    received: "ReÃ§ue",
    accepted: "AcceptÃ©e",
    preparing: "En prÃ©paration",
    ready: "PrÃªte",
    pickedUp: "RetirÃ©e",
    cancelled: "AnnulÃ©e",
    expired: "ExpirÃ©e",
  },
  rewards: {
    title: "RÃ©compenses",
    subtitle: "5 achats qualifiants = 1 boisson offerte.",
    stampRequestTitle: "Demander un point fid\u00e9lit\u00e9",
    stampRequestBody:
      "Si vous venez de payer au comptoir, envoyez une demande rapide au barista pour valider votre point fid\u00e9lit\u00e9.",
    stampRequestAction: "Demander un point",
    stampRequestSentLabel: "Demande envoy\u00e9e",
    stampRequestSent: "Votre demande de point a \u00e9t\u00e9 envoy\u00e9e au comptoir.",
    stampRequestAlreadyPending: "Une demande de point est d\u00e9j\u00e0 en attente.",
    stampRequestPending: (date: string) => `Demande de point envoy\u00e9e le ${date}.`,
    unlockedTitle: "Boisson offerte dÃ©bloquÃ©e",
    unlockedBody: "Votre crÃ©dit est stockÃ© dans le compte et peut Ãªtre utilisÃ© plus tard.",
    available: "Disponible",
    historyTitle: "Historique fidÃ©litÃ©",
    stampLabel: "Points fid\u00e9lit\u00e9",
    freeDrinkLabel: "Boisson offerte",
  },
  account: {
    title: "Compte",
    subtitle: "Informations rapides pour un retour sans friction.",
    logoutBody: "DÃ©connectez-vous seulement si nÃ©cessaire.",
    memberIdBody: "Partagez cet ID membre au barista pour retrouver votre compte plus vite.",
    recoveryCodeTitle: "Code de secours",
    recoveryCodeSummary: "Afficher le code de secours",
    recoveryCodeBody:
      "Gardez ce code seulement pour vous reconnecter sur un nouvel appareil. Il n'est pas utile au quotidien sur ce tÃ©lÃ©phone.",
  },
  access: {
    title: "Continuer avec votre numéro",
    body: (name: string) =>
      `Bonjour ${name}, confirmez votre numéro pour ouvrir votre accès sécurisé.`,
    linkHint:
      "Ce lien est personnel, valable peu de temps et utilisable une seule fois.",
    phoneHint:
      "Entrez le même numéro que celui communiqué au comptoir pour continuer.",
    invalidTitle: "Lien indisponible",
    invalidBody:
      "Ce lien n'est plus valable. Demandez-en un nouveau au comptoir si besoin.",
  },
  history: {
    title: "Historique",
    subtitle: "Vos derniÃ¨res commandes et un raccourci pour recommander.",
  },
  staff: {
    loginTitle: "Connexion Ã©quipe",
    queueTitle: "File des commandes",
    queueSubtitle: "Les nouvelles commandes doivent rester visibles et simples Ã  traiter.",
    detailTitle: "DÃ©tail commande",
    customerTitle: "Fiche client",
    customerCreateTitle: "Ajouter un client",
    customerCreateBody:
      "CrÃ©ez une fiche fidÃ©litÃ© immÃ©diatement, mÃªme si le client nâ€™a pas son tÃ©lÃ©phone avec lui.",
    customerCreateSuccess: (name: string, memberId: string) =>
      `${name} a Ã©tÃ© ajoutÃ© avec lâ€™ID membre ${memberId}.`,
    customerCreateSmsHint:
      "Optionnel : préparez un SMS avec un lien d'accès unique pour que le client ouvre son compte plus tard.",
    customerCreateDetailAction: "Ouvrir la fiche",
    recoveryCodeTitle: "Code de secours",
    recoveryCodeBody:
      "Ã€ transmettre seulement si le client veut ouvrir son compte sur un nouvel appareil.",
    customerSmsMessage: (name: string, accessUrl: string) =>
      `Bonjour ${name}, votre accès Riwak est prêt. Ouvrez ce lien unique : ${accessUrl}. Continuez ensuite avec votre numéro de téléphone.`,
    trustTitle: "Gestion du niveau de confiance",
    loyaltyTitle: "Vue fidÃ©litÃ©",
    settingsTitle: "RÃ©glages boutique",
    metricsTitle: "AperÃ§u rapide",
    filtersTitle: "Filtres",
    incomingLabel: "Nouvelle",
    activeUnpaidLabel: "Commande impayÃ©e active",
    customerSearchTitle: "Rechercher un client",
    stampRequestTitle: "Demandes de tampon",
    stampRequestBody:
      "Validez rapidement les passages envoyÃ©s depuis lâ€™app client. Une seule demande peut rester en attente par client.",
    stampRequestPending: "En attente",
    stampRequestApprove: "Approuver",
    stampRequestHandled: "Cette demande a dÃ©jÃ  Ã©tÃ© traitÃ©e.",
    customerSearchEmpty: "Aucun client ne correspond Ã  cette recherche.",
    logoutTitle: "Session Ã©quipe",
    logoutBody:
      "DÃ©connectez le tÃ©lÃ©phone ou la tablette partagÃ©e Ã  la fin du service.",
    logoutAction: "DÃ©connecter",
    quickStampAdded: (count: number) =>
      count === 1 ? "+1 tampon ajoutÃ©." : `+${count} tampons ajoutÃ©s.`,
    rewardRedeemed: "RÃ©compense utilisÃ©e.",
  },
  forms: {
    phonePlaceholder: "06 12 34 56 78",
    namePlaceholder: "Nom et prÃ©nom",
    emailPlaceholder: "staff@riwak.ma",
    passwordPlaceholder: "â€¢â€¢â€¢â€¢â€¢â€¢â€¢â€¢",
    pinPlaceholder: "123456",
    notesPlaceholder: "Ex. peu de sucre, sans mousse",
    storeNamePlaceholder: "Riwak Coffee",
    addressPlaceholder: "Adresse de retrait",
    pricePlaceholder: "Prix",
    displayOrderPlaceholder: "Ordre dâ€™affichage",
    customerSearchPlaceholder: "ID membre, tÃ©lÃ©phone ou nom",
  },
  statuses: {
    received: "ReÃ§ue",
    accepted: "AcceptÃ©e",
    preparing: "En prÃ©paration",
    ready: "PrÃªte",
    pickedUp: "RetirÃ©e",
    cancelled: "AnnulÃ©e",
    expired: "ExpirÃ©e",
  },
  customerTypes: {
    new: "Nouveau",
    returning: "Retour",
    trusted: "RÃ©gulier de confiance",
    limited: "LimitÃ© / suspect",
  },
  trustActions: {
    trusted: "Marquer comme rÃ©gulier",
    limited: "Limiter temporairement",
    clearLimit: "Lever la limitation",
    note: "Ajouter une note",
  },
  loyalty: {
    earned: "Point gagn\u00e9",
    redeemed: "Boisson offerte utilisÃ©e",
    adjusted: "Ajustement manuel",
    progress: (current: number, threshold: number) => `${current} sur ${threshold} points`,
    availableRewards: (count: number) => `${count} boisson${count > 1 ? "s" : ""} offerte${count > 1 ? "s" : ""}`,
  },
  empty: {
    menu: "Le menu est vide pour le moment.",
    orders: "Aucune commande pour ce filtre.",
    customers: "Aucun client pour le moment.",
    rewards: "Aucune rÃ©compense pour le moment.",
    history: "Aucun historique pour le moment.",
    noOrderYet: "Pas encore de commande.",
  },
  install: {
    title: "Ajouter Ã  lâ€™Ã©cran dâ€™accueil",
    body:
      "Sur tÃ©lÃ©phone, ajoutez Riwak Ã  lâ€™Ã©cran dâ€™accueil pour une ouverture plus rapide et plus fiable dans la boutique.",
    iosHint: "Sur iPhone, utilisez le bouton Partager puis Â« Ajouter Ã  lâ€™Ã©cran dâ€™accueil Â».",
  },
  setup: {
    title: "Finalisez votre accÃ¨s",
    body:
      "Deux rÃ©glages utiles pour ouvrir Riwak plus vite et recevoir les alertes importantes.",
    installTitle: "Ajouter lâ€™app",
    installBody: "Gardez Riwak Ã  portÃ©e de main sur lâ€™Ã©cran dâ€™accueil.",
    installManualHint:
      "Sur iPhone, utilisez Partager puis Â« Ajouter Ã  lâ€™Ã©cran dâ€™accueil Â», puis revenez ici.",
    installDoneAction: "Câ€™est fait",
    notificationsTitle: "Activer les notifications",
    notificationsBody:
      "Recevez une alerte quand votre commande est prÃªte et quand une boisson offerte est dÃ©bloquÃ©e.",
    notificationsDenied:
      "Les notifications sont bloquÃ©es sur ce navigateur. Vous pourrez les activer plus tard dans les rÃ©glages.",
  },
  notifications: {
    enable: "Activer les notifications",
    disable: "DÃ©sactiver les notifications",
    pending: "Mise Ã  jour...",
    unsupported: "Les notifications ne sont pas disponibles sur ce navigateur.",
    unavailable: "Les notifications push ne sont pas configurÃ©es pour le moment.",
    permissionDenied:
      "Les notifications sont bloquÃ©es. Activez-les depuis les rÃ©glages du navigateur.",
    customer: {
      title: "Notifications de commande",
      description:
        "Recevez une alerte quand votre commande est prÃªte et quand une boisson offerte est dÃ©bloquÃ©e.",
      enabled:
        "Les alertes de commande et de rÃ©compense sont actives sur cet appareil.",
    },
    staff: {
      title: "Notifications barista",
      description:
        "Recevez une alerte quand une nouvelle commande arrive, mÃªme si la file n'est pas ouverte.",
      enabled:
        "Les alertes de nouvelle commande sont actives sur cet appareil.",
    },
    errors: {
      subscribeFailed: "Impossible d'activer les notifications pour le moment.",
      unsubscribeFailed: "Impossible de dÃ©sactiver les notifications pour le moment.",
    },
  },
  settings: {
    title: "ParamÃ¨tres",
    subtitle: "GÃ©rez le menu et les rÃ¨gles sans toucher Ã  lâ€™architecture.",
    rulesTitle: "RÃ¨gles boutique",
    menuTitle: "Articles du menu",
    businessRulesTitle: "RÃ¨gles anti-abus",
    saveSuccess: "RÃ©glages enregistrÃ©s.",
  },
  errors: {
    BAD_FORM: "Le formulaire est incomplet.",
    BAD_PHONE: "Le numÃ©ro de tÃ©lÃ©phone est invalide.",
    PHONE_EXISTS: "Un compte existe dÃ©jÃ  avec ce numÃ©ro.",
    INVALID_PIN: "Le tÃ©lÃ©phone ou le PIN est incorrect.",
    INVALID_CREDENTIALS: "Identifiants Ã©quipe incorrects.",
    NOT_AUTHENTICATED: "Vous devez vous connecter dâ€™abord.",
    MENU_INACTIVE: "Cet article nâ€™est pas disponible.",
    ACTIVE_ORDER_LIMIT: "Vous avez dÃ©jÃ  une commande active.",
    VOICE_NOTE_UNAVAILABLE: "Le message vocal est indisponible pour le moment.",
    VOICE_NOTE_TOO_LARGE: "Le message vocal est trop lourd. Gardez-le trÃ¨s court.",
    NOT_FOUND: "Ã‰lÃ©ment introuvable.",
    NO_REWARD: "Aucune rÃ©compense disponible pour le moment.",
    LIMIT_REACHED: "Ce compte est temporairement limitÃ©.",
    MISSING_ITEM: "SÃ©lectionnez un article avant de continuer.",
    ORDER_EXPIRED: "Cette commande a expirÃ©.",
    ACCESS_LINK_INVALID: "Ce lien d'accès n'est plus valable. Demandez-en un nouveau au comptoir.",
    UNKNOWN: "Une erreur est survenue.",
  },
  labels: {
    qualifying: "Qualifie pour un tampon",
    optional: "Optionnel",
    required: "Obligatoire",
    activeOrder: "Commande active",
    favorite: "Favori",
    recent: "RÃ©cent",
    quickAction: "Action rapide",
  },
} as const;

export type FrenchContent = typeof fr;


