export const fr = {
  appName: "riwak",
  tagline: "Commande rapide et fidélité pour le café",
  brand: {
    short: "riwak",
    full: "Riwak Coffee",
  },
  actions: {
    register: "Créer mon compte",
    login: "Se connecter",
    logout: "Se déconnecter",
    orderNow: "Commander maintenant",
    viewOrder: "Voir la commande",
    addToHome: "Ajouter à l’écran d’accueil",
    dismiss: "Plus tard",
    redeem: "Utiliser",
    save: "Enregistrer",
    edit: "Modifier",
    add: "Ajouter",
    refresh: "Actualiser",
    back: "Retour",
    confirm: "Confirmer",
    cancel: "Annuler",
    continue: "Continuer",
    quickReorder: "Recommander",
    markTrusted: "Marquer comme régulier",
    markLimited: "Limiter",
  },
  common: {
    loading: "Chargement…",
    search: "Rechercher",
    notesOptional: "Notes, si besoin",
    noResults: "Aucun résultat pour le moment.",
    emptyState: "Rien à afficher pour l’instant.",
    active: "Actif",
    inactive: "Inactif",
    today: "Aujourd’hui",
    now: "Maintenant",
    minutesShort: "min",
    quantity: "Quantité",
    pickupTime: "Heure de retrait",
    pickupAddress: "Adresse de retrait",
    phoneNumber: "Numéro de téléphone",
    fullName: "Nom complet",
    loyaltyPin: "PIN fidélité",
    password: "Mot de passe",
    email: "E-mail",
    price: "Prix",
    status: "Statut",
  },
  navCustomer: {
    home: "Accueil",
    menu: "Menu",
    rewards: "Récompenses",
    account: "Compte",
  },
  navStaff: {
    orders: "Commandes",
    customers: "Clients",
    loyalty: "Fidélité",
    settings: "Réglages",
  },
  landing: {
    eyebrow: "Commande mobile",
    title: "Riwak simplifie la pause café.",
    subtitle:
      "Commandez en avance, payez au comptoir, récupérez vite. Fidélité simple, PIN automatique, interface pensée pour le téléphone.",
    registerCardTitle: "Nouveau client",
    registerCardBody: "Créez votre compte en moins d’une minute.",
    returningCardTitle: "Déjà inscrit ?",
    returningCardBody: "Retrouvez votre compte avec votre téléphone et votre PIN.",
    staffCardTitle: "Espace équipe",
    staffCardBody: "Accès barista et admin pour les commandes et le suivi client.",
    installHintTitle: "Ajouter l’app",
    installHintBody:
      "Gardez Riwak sur l’écran d’accueil pour ouvrir l’app plus vite, même en boutique bondée.",
  },
  auth: {
    registerTitle: "Créer votre compte client",
    registerBody:
      "Entrez votre nom et votre numéro. Le PIN fidélité est créé automatiquement.",
    loginTitle: "Connexion rapide",
    loginBody: "Utilisez votre téléphone et votre PIN fidélité.",
    staffLoginTitle: "Connexion équipe",
    staffLoginBody: "Accès sécurisé pour le personnel et l’admin.",
    staffPasswordHint: "Le mot de passe est réservé à l’équipe.",
    pinHelp:
      "Conservez ce PIN. Il permet un accès rapide sur ce téléphone sans OTP.",
  },
  home: {
    greeting: (name: string) => `Bonjour, ${name}`,
    orderCardTitle: "Commander vite",
    orderCardBody: "Choisissez un article et un créneau de retrait.",
    activeOrderTitle: "Commande en cours",
    activeOrderBody: "Votre commande est déjà en route.",
    loyaltyTitle: "Fidélité",
    rewardTitle: "Récompense disponible",
    recentOrderTitle: "Dernière commande",
    favoriteOrderTitle: "Commande favorite",
    pinCardTitle: "Votre PIN",
    trustCardTitle: "Niveau client",
  },
  menu: {
    title: "Menu",
    subtitle: "Une carte courte, rapide à lire, facile à configurer.",
    detailTitle: "Détail de l’article",
    detailBody: "Sélectionnez la quantité et ajoutez une note seulement si nécessaire.",
    orderButton: "Choisir le retrait",
  },
  order: {
    reviewTitle: "Vérification de la commande",
    reviewBody: "Relisez, choisissez l’heure de retrait, puis validez.",
    successTitle: "Commande envoyée",
    successBody: "L’équipe voit la commande tout de suite.",
    liveStatusTitle: "Suivi de commande",
    liveStatusBody: "Suivez l’état en temps réel sur votre téléphone.",
    pickupNow: "Retrait maintenant",
    pickupIn: (minutes: number) => `Retrait dans ${minutes} min`,
    received: "Reçue",
    accepted: "Acceptée",
    preparing: "En préparation",
    ready: "Prête",
    pickedUp: "Retirée",
    cancelled: "Annulée",
    expired: "Expirée",
  },
  rewards: {
    title: "Récompenses",
    subtitle: "5 achats qualifiants = 1 boisson offerte.",
    unlockedTitle: "Boisson offerte débloquée",
    unlockedBody: "Votre crédit est stocké dans le compte et peut être utilisé plus tard.",
    available: "Disponible",
    historyTitle: "Historique fidélité",
    stampLabel: "Tampons",
    freeDrinkLabel: "Boisson offerte",
  },
  account: {
    title: "Compte",
    subtitle: "Informations rapides pour un retour sans friction.",
    logoutBody: "Déconnectez-vous seulement si nécessaire.",
  },
  history: {
    title: "Historique",
    subtitle: "Vos dernières commandes et un raccourci pour recommander.",
  },
  staff: {
    loginTitle: "Connexion équipe",
    queueTitle: "File des commandes",
    queueSubtitle: "Les nouvelles commandes doivent rester visibles et simples à traiter.",
    detailTitle: "Détail commande",
    customerTitle: "Fiche client",
    trustTitle: "Gestion du niveau de confiance",
    loyaltyTitle: "Vue fidélité",
    settingsTitle: "Réglages boutique",
    metricsTitle: "Aperçu rapide",
    filtersTitle: "Filtres",
    incomingLabel: "Nouvelle",
    activeUnpaidLabel: "Commande impayée active",
  },
  forms: {
    phonePlaceholder: "06 12 34 56 78",
    namePlaceholder: "Nom et prénom",
    emailPlaceholder: "staff@riwak.ma",
    passwordPlaceholder: "••••••••",
    pinPlaceholder: "123456",
    notesPlaceholder: "Ex. peu de sucre, sans mousse",
    storeNamePlaceholder: "Riwak Coffee",
    addressPlaceholder: "Adresse de retrait",
    pricePlaceholder: "Prix",
    displayOrderPlaceholder: "Ordre d’affichage",
  },
  statuses: {
    received: "Reçue",
    accepted: "Acceptée",
    preparing: "En préparation",
    ready: "Prête",
    pickedUp: "Retirée",
    cancelled: "Annulée",
    expired: "Expirée",
  },
  customerTypes: {
    new: "Nouveau",
    returning: "Retour",
    trusted: "Régulier de confiance",
    limited: "Limité / suspect",
  },
  trustActions: {
    trusted: "Marquer comme régulier",
    limited: "Limiter temporairement",
    clearLimit: "Lever la limitation",
    note: "Ajouter une note",
  },
  loyalty: {
    earned: "Tampon gagné",
    redeemed: "Boisson offerte utilisée",
    adjusted: "Ajustement manuel",
    progress: (current: number, threshold: number) => `${current} sur ${threshold} tampons`,
    availableRewards: (count: number) => `${count} boisson${count > 1 ? "s" : ""} offerte${count > 1 ? "s" : ""}`,
  },
  empty: {
    menu: "Le menu est vide pour le moment.",
    orders: "Aucune commande pour ce filtre.",
    customers: "Aucun client pour le moment.",
    rewards: "Aucune récompense pour le moment.",
    history: "Aucun historique pour le moment.",
  },
  install: {
    title: "Ajouter à l’écran d’accueil",
    body:
      "Sur téléphone, ajoutez Riwak à l’écran d’accueil pour une ouverture plus rapide et plus fiable dans la boutique.",
    iosHint: "Sur iPhone, utilisez le bouton Partager puis « Ajouter à l’écran d’accueil ».",
  },
  settings: {
    title: "Paramètres",
    subtitle: "Gérez le menu et les règles sans toucher à l’architecture.",
    rulesTitle: "Règles boutique",
    menuTitle: "Articles du menu",
    businessRulesTitle: "Règles anti-abus",
    saveSuccess: "Réglages enregistrés.",
  },
  errors: {
    BAD_FORM: "Le formulaire est incomplet.",
    BAD_PHONE: "Le numéro de téléphone est invalide.",
    PHONE_EXISTS: "Un compte existe déjà avec ce numéro.",
    INVALID_PIN: "Le téléphone ou le PIN est incorrect.",
    INVALID_CREDENTIALS: "Identifiants équipe incorrects.",
    NOT_AUTHENTICATED: "Vous devez vous connecter d’abord.",
    MENU_INACTIVE: "Cet article n’est pas disponible.",
    ACTIVE_ORDER_LIMIT: "Vous avez déjà une commande active.",
    NOT_FOUND: "Élément introuvable.",
    NO_REWARD: "Aucune récompense disponible pour le moment.",
    LIMIT_REACHED: "Ce compte est temporairement limité.",
    MISSING_ITEM: "Sélectionnez un article avant de continuer.",
    ORDER_EXPIRED: "Cette commande a expiré.",
    UNKNOWN: "Une erreur est survenue.",
  },
  labels: {
    qualifying: "Qualifie pour un tampon",
    optional: "Optionnel",
    required: "Obligatoire",
    activeOrder: "Commande active",
    favorite: "Favori",
    recent: "Récent",
    quickAction: "Action rapide",
  },
} as const;

export type FrenchContent = typeof fr;
